# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.4+3

environment:
  sdk: ^3.6.1

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # Cupertino style icons
  cupertino_icons: ^1.0.8
  #Getx
  get: ^4.7.3
  #size util 
  flutter_screenutil: ^5.9.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.5.0

  # Encourages good practices
  flutter_lints: ^5.0.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/